apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pm-grist-dev-postgresql
spec:
  destination:
    namespace: {{ .Release.Namespace | quote }}
    name: ovh-prod-c4
  project: {{ .Release.Namespace | quote }}
  source:
    path: components/postgresql
    repoURL: https://gitlab.apps.c6.numerique-interieur.com/forge-mi/projects/pm/grist/gristinfra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
