redis:
  master:
    resources:
      requests:
        cpu: 1
        memory: 256Mi
      limits:
        cpu: 1
        memory: 256Mi
    podSecurityContext:
      fsGroup: 1001390000
    containerSecurityContext:
      runAsUser: 1001390000
      runAsGroup: 1001390000
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis
    existingSecretPasswordKey: password

commonEnvVars: &commonEnvVars
  REDIS_URL:
    secretKeyRef:
      name: redis
      key: url
  GRIST_TEMPLATE_ORG: templates
  GRIST_USE_ENGINE_IO: "1"
  GRIST_ORG_IN_PATH: "true"
  GRIST_DEFAULT_EMAIL: "admin@example.org"
  GRIST_SANDBOX_FLAVOR: gvisor
  GRIST_HIDE_UI_ELEMENTS: billing
  APP_STATIC_INCLUDE_CUSTOM_CSS: true
  GRIST_DEFAULT_LOCALE: fr
  GRIST_HELP_CENTER: https://outline.incubateur.anct.gouv.fr/doc/documentation-grist-YPWlYTHa8j
  GRIST_ANON_PLAYGROUND: false
  PERMITTED_CUSTOM_WIDGETS: "calendar"
  TYPEORM_TYPE: postgres
  TYPEORM_DATABASE: grist
  TYPEORM_EXTRA: '{"ssl": true, "extra": {"ssl": {"rejectUnauthorized": false}}}'
  TYPEORM_HOST:
    secretKeyRef:
      name: postgresql
      key: host
  TYPEORM_USERNAME:
    secretKeyRef:
      name: postgresql
      key: username
  TYPEORM_PASSWORD:
    secretKeyRef:
      name: postgresql
      key: password
  GRIST_SINGLE_PORT: 0

grist:
  ingress:
    host: grist-dinum-test.dev.numerique-interieur.com
  
  homeWorker:
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
    replicas: 1
    envVars:
      <<: *commonEnvVars
      GRIST_SERVERS: home,static
    securityContext:
      runAsUser: 1001390001
      runAsGroup: 1001390001

  docWorker:
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
    replicas: 1
    envVars:
      <<: *commonEnvVars
      GRIST_DOCS_MINIO_PORT: 443
      GRIST_DOCS_MINIO_USE_SSL: 1
      GRIST_SERVERS: docs
      GRIST_DOCS_MINIO_BUCKET:
        secretKeyRef:
          name: minio
          key: minioBucket
      GRIST_DOCS_MINIO_ENDPOINT:
        secretKeyRef:
          name: minio
          key: endpoint
      GRIST_DOCS_MINIO_BUCKET_REGION: local
      GRIST_DOCS_MINIO_ACCESS_KEY:
        secretKeyRef:
          name: minio
          key: accessKey
      GRIST_DOCS_MINIO_SECRET_KEY:
        secretKeyRef:
          name: minio
          key: secretKey
    persistence:
      persit:
        type: emptyDir
        mountPath: /persist
    securityContext:
      runAsUser: 1001390001
      runAsGroup: 1001390001
    shareProcessNamespace: true
