apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Pkavm9v9Uv/BnQ==,iv:2FNyBeD4UzlC7gU7mX2daB/Nao56BNQHW71PRUQe8/0=,tag:uHCGT0Hr1Kx942eRR8OBqQ==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:OWNXwGU=,iv:fZ4ZMF659XWkGpa3/7j84LNnvqNANPJ61a7hmJqc41s=,tag:5gmlTi91Wr9YbhJStC+obg==,type:str]
            password: ENC[AES256_GCM,data:c7SAUdOxNjUTzeFk3JQ=,iv:QK5DcZPVQfMjHJIie7d+Ad96Goh4LH5oSwhEid/YiZI=,tag:uEy1McWzCZH63aDqCxNuZg==,type:str]
            host: ENC[AES256_GCM,data:A60wECEDtxEf7TavZQ==,iv:4ai8cwkqh9waAZ4H4+Jgz+jpUaA+NSt4lnHO2f7y62o=,tag:SWgVvtgxpN4+KvOAsWL/xw==,type:str]
        - name: ENC[AES256_GCM,data:LfYmsqY=,iv:UjxTNPW28dspc48x8eSugxM7yR6xPKRxGDzMBCYoZEg=,tag:kkpEU8DOmicx2e7X/i+X9w==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:dHCgxE3YNJkJa6APKEU=,iv:JbCZ0o74O+4eMSvjXF8yBjYdPPwGHxYPMc7A1S2oJS8=,tag:q7/0QAZQbBTa7liZAFGNYg==,type:str]
            url: ENC[AES256_GCM,data:Yl26ddMd3FrW5Az2CXFUv+E9dfjnQX6J7lv+FOTS8ih4puw6K8O8jkVANons5L4xy7agt708k6eR3x/A/8jv6g/fusLiUA==,iv:Tdg5Rj/gNzBZ7QAAv6EphxmnHtda3aYV0+Hv+zY6EWg=,tag:5A5JtD5h+5xGIoeuRgdsWA==,type:str]
        - name: ENC[AES256_GCM,data:S6Ucoufg,iv:DbxMYc6acPWcJTCt+hG55nZZgBFGugDHZ3Xobeyhal8=,tag:h4ZScrlSO+KNsOlOSiLITw==,type:str]
          stringData:
            secretKey: ENC[AES256_GCM,data:Rw2AJC29nqxCLWAkVPg=,iv:7uoueYKC4/tl/fhHdb/Usx41rN2Hy6NCt5ffl6XQGbc=,tag:97DTQNwGrSYJRZxRjkw/BA==,type:str]
            accessKey: ENC[AES256_GCM,data:uvnRjRI=,iv:okinceiKcN5wp2LlRwnnT8BlvznWgG6GvRV/MXJ2cIw=,tag:4/xESgy2fH0gGxPgCnEb6Q==,type:str]
            endpoint: ENC[AES256_GCM,data:eNzhclblfugdTyww48iuGRAVE3oWFev/1BkOE8WUWy+RvIctWNbGq4eQNg==,iv:UKTxJE0wEp0mumrNRc/tZgcpa2LKNwVov74XFDlR9Xk=,tag:/my8lOr5rV7CvqL1+y9Kjg==,type:str]
            bucket: ENC[AES256_GCM,data:NQ+Qbyo=,iv:RVehUkNwqszIOSQ5ATZGbXL2JjI/q6JW/tqvjJzofbY=,tag:STMYD0OnG5MUQZCDMjOA8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NUNXWUFGRWNFS3pUSWI0
            b1FjRW1aTlZsd1N3cGQxTnV2VjFnRk14R3dVCld3MXlRdU1nVTlQTW41U2RYclg0
            aVFhMlFUL0dJZkZISEdXOGtBcGdEMncKLS0tIFh3WVhMWCttZzlmdlY3Z0lBTmdH
            eGI2clVaRkdLWXRtY0ZCemNXYUJSMUEKtDuXPvSMNu70graPn8suP5/+mHz0gUPQ
            RmSqWsXVbf9Y8r8Hv3aHeddjEsUBmPh7MlVys8UEjM4K+7tnuw4MEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK1FRNEtNLzMwdERzZDNz
            QUNQTjF0Ym9DaDBFMzhTZ1Y3cy9DQ29TN1UwClRta282K0cwZllsQkFXRVU0VmlN
            RVBaWnJHemJzazE2Sm1nOHZhbXQ3MEkKLS0tIFFZK2RXOUJaakVYTXF4ZTNyeUJH
            M0NpY2RtUGxpd2xBUVdMQTU1Qzk1TUkK+Gu/jbZU93QCQ/vZgwKz3BIs8s6iYfgU
            n9V2ZH+j1DAqBswHK1yyINToFV96xUCs7MhXdzxWpZJVt32xA5nn+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T16:40:23Z"
    mac: ENC[AES256_GCM,data:dVdDMSlg9eriTUIuw56kYKLtoln9KcE0AAtZK3bWD074hqre+t7/aA2hgNeqZk26l9bRZRCUVfypgXV5qnGBExNob5pXUuZhZL1t6vskOS8QTuUQUiQyB1x3xfFwoaz6g1uAfy2lHWYuq9dU1QkYD/9oqQT/X4ksVDbOPo+R+CY=,iv:YGP03uN43QToUuJmV68lLq38/ZSD4Vj+9V8rmrXVOXs=,tag:hjCqgXec+mqiX1SEJvdiRw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
